CREATE TABLE Employee (
	Employee_ID NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1,
	FirstName VARCHAR2(20) NOT NULL,
	LastName VARCHAR2(20) NOT NULL,
	Salary DECIMAL(10,2),	
	JobTitle VARCHAR2(15) NOT NULL,
	Manager_ID NUMBER ,
	Address VARCHAR2(20) NOT NULL,
	Hire_Date  DATE,
	Department_ID NUMBER NOT NULL,
    CONSTRAINT FK_MANAGER FOREIGN KEY(Manager_ID) REFERENCES Employee(Employee_ID),
    CONSTRAINT FK_DEPARTMENT FOREIGN KEY(Department_ID) REFERENCES Department(Deparment_ID),
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (Employee_ID)
)

CREATE TABLE Department (
	Deparment_ID NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1,
	Name VARCHAR2(20) NOT NULL,
	Town_Name VARCHAR2(20) NOT NULL  ,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (Deparment_ID)
);

CREATE TABLE Clients(
	Client_ID NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1,
	Username VARCHAR2(20) NOT NULL,
	Password VARCHAR2(10) NOT NULL,
	Last_Login DATE,
    CONSTRAINT PK_CLIENT_ID PRIMARY KEY (Client_ID)
);

INSERT INTO Department(Name,Town_Name)
VALUES('Sales','Plovdiv');

INSERT INTO Department(Name,Town_Name)
VALUES('Finance','Sofia');

INSERT INTO Department(Name,Town_Name)
VALUES('HR','Varna');

INSERT INTO Employee(FirstName,LastName,Salary,JobTitle,Address,Hire_Date, Department_ID)
VALUES
('Kosara','Tsenkova',2000,'Manager','Plovdiv',TO_DATE('2003/07/09', 'yyyy/mm/dd'),1 );

INSERT INTO Employee(FirstName,LastName,Salary,JobTitle,Address,Hire_Date, Department_ID)
VALUES
('Tsvetelina','Tsenkova',5000,'Manager','Sofia',TO_DATE('1998-09-09', 'yyyy/mm/dd'),2 );

INSERT INTO Employee(FirstName,LastName,Salary,JobTitle,Manager_ID,Address,Hire_Date, Department_ID)
VALUES
('Victoria','Raztsvetnikova',2500,'Senior',5,'Varna',TO_DATE('2011-11-11', 'yyyy/mm/dd'),2 );


INSERT INTO Employee(FirstName,LastName,Salary,JobTitle,Manager_ID,Address,Hire_Date, Department_ID)
VALUES
('Stefani','Stefanova',3000,'Junior',8,'Plovdiv',TO_DATE('2009-09-09', 'yyyy/mm/dd'),3 );

INSERT INTO Employee(FirstName,LastName,Salary,JobTitle,Manager_ID,Address,Hire_Date, Department_ID)
VALUES
('Ivanka','Ivanova',5000,'Senior',8,'Pernik',TO_DATE('1996-09-09', 'yyyy/mm/dd'),3 );


INSERT INTO Clients(Username,Password,Last_Login)
VALUES('Ivan','12345',TO_DATE('2019-03-03', 'yyyy/mm/dd'));

INSERT INTO Clients(Username,Password,Last_Login)
VALUES('Pesho','12345',TO_DATE('2020-02-03', 'yyyy/mm/dd'));

INSERT INTO Clients(Username,Password,Last_Login)
VALUES('Gosho','12345',TO_DATE('2020-01-01', 'yyyy/mm/dd'));



/*?	Find information about all departments names*/
SELECT Name FROM Department;

/*?	Find the salary of each employee*/
SELECT Salary FROM Employee;

/*?	Find the full name of each employee*/
SELECT FirstName, LastName 
FROM Employee;

/*?	Create a query that produces an employ email address by using the employee first and last name. 
The user E-mail consists of first name and last name concatenated by a full stop. The domain of the E-mail is fakecompany.com. 
The result must be produced in a separate column named Full name*/
SELECT CONCAT(CONCAT(FirstName, LastName),'fakecompany.com')
FROM Employee;

/*?	Find all employ with job title Senior executive*/
SELECT * FROM Employee
WHERE JobTitle = 'Senior';

/*?	Find all employs with name starts with letter S*/
SELECT * FROM Employee
WHERE FirstName LIKE 'S__%';

/*?	Find all employees with a name that contains the letter l*/
SELECT * FROM Employee
WHERE FirstName LIKE '%l%';

/*?	Find all employees that have a salary in the range 2000 – 3000*/
SELECT * FROM Employee
WHERE Salary < 3000 AND Salary > 2000;

/*?	Find all employees that have salaries 2500 / 3000 / 3500 / 5000*/
SELECT * FROM Employee
WHERE Salary = 2500 OR Salary = 3000 OR Salary = 3500 OR Salary = 5000;

/*?	Find all employees that do not have a manager*/
SELECT * FROM Employee
WHERE Manager_ID IS NULL;

/*?	Find all employees that have a senior position in the company and have a salary greater than 5000.
Order them in decreasing order and by alphabetical order by there first name.*/
SELECT * FROM Employee 
WHERE JobTitle = 'Senior' AND Salary > 5000
ORDER BY FirstName;

/*?	Find the top 5 best-paid employees.*/
SELECT *
FROM (select * from Employee ORDER BY Salary DESC) suppliers2
WHERE rownum <= 5
ORDER BY rownum;

/*?	Find all employees and their addresses*/
SELECT FirstName, Address 
FROM Employee;

/*?	Find all employees and their manager*/
SELECT E.FirstName,M.FirstName
FROM EMPLOYEE E  JOIN EMPLOYEE M
ON E.MANAGER_ID = M.EMPLOYEE_ID
GROUP BY E.FirstName,M.FirstName;

/*?	Find all employees along with their manager and address*/
SELECT E.FirstName,M.FirstName,M.Address
FROM EMPLOYEE E  JOIN EMPLOYEE M
ON E.MANAGER_ID = M.EMPLOYEE_ID
GROUP BY E.FirstName,M.FirstName,M.Address;

/*?	Find all departments and all town names as a single list*/




