CREATE TABLE Employee (
	Employee_ID NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1,
	FirstName VARCHAR2(20) NOT NULL,
	LastName VARCHAR2(20) NOT NULL,
	Salary DECIMAL(10,2),	
	JobTitle VARCHAR2(15) NOT NULL,
	Manager_ID NUMBER ,
	Address VARCHAR2(20) NOT NULL,
	Hire_Date  DATE,
	Department_ID NUMBER NOT NULL,
    CONSTRAINT FK_MANAGER FOREIGN KEY(Manager_ID) REFERENCES Employee(Employee_ID),
    CONSTRAINT FK_DEPARTMENT FOREIGN KEY(Department_ID) REFERENCES Department(Deparment_ID),
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (Employee_ID)
)

CREATE TABLE Department (
	Deparment_ID NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1,
	Name VARCHAR2(20) NOT NULL,
	Town_Name VARCHAR2(20) NOT NULL  ,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (Deparment_ID)
);

CREATE TABLE Clients(
	Client_ID NUMBER  GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 1,
	Username VARCHAR2(20) NOT NULL,
	Password VARCHAR2(10) NOT NULL,
	Last_Login DATE,
    CONSTRAINT PK_CLIENT_ID PRIMARY KEY (Client_ID)
);

INSERT INTO Department(Name,Town_Name)
VALUES('Sales','Plovdiv');

INSERT INTO Department(Name,Town_Name)
VALUES('Finance','Sofia');

INSERT INTO Department(Name,Town_Name)
VALUES('HR','Varna');

INSERT INTO Employee(FirstName,LastName,Salary,JobTitle,Address,Hire_Date, Department_ID)
VALUES
('Kosara','Tsenkova',2000,'Manager','Plovdiv',TO_DATE('2003/07/09', 'yyyy/mm/dd'),1 );

INSERT INTO Employee(FirstName,LastName,Salary,JobTitle,Address,Hire_Date, Department_ID)
VALUES
('Tsvetelina','Tsenkova',5000,'Manager','Sofia',TO_DATE('1998-09-09', 'yyyy/mm/dd'),2 );

INSERT INTO Employee(FirstName,LastName,Salary,JobTitle,Manager_ID,Address,Hire_Date, Department_ID)
VALUES
('Victoria','Raztsvetnikova',2500,'Senior',5,'Varna',TO_DATE('2011-11-11', 'yyyy/mm/dd'),2 );

INSERT INTO Employee(FirstName,LastName,Salary,JobTitle,Manager_ID,Address,Hire_Date, Department_ID)
VALUES
('Stefani','Stefanova',3000,'Junior',8,'Plovdiv',TO_DATE('2009-09-09', 'yyyy/mm/dd'),3 );

INSERT INTO Employee(FirstName,LastName,Salary,JobTitle,Manager_ID,Address,Hire_Date, Department_ID)
VALUES
('Ivanka','Ivanova',5000,'Senior',8,'Pernik',TO_DATE('1996-09-09', 'yyyy/mm/dd'),3 );

INSERT INTO Employee(FirstName,LastName,Salary,JobTitle,Manager_ID,Address,Hire_Date, Department_ID)
VALUES
('Sashka','Sashkova',5000,'Junior',8,'Pernik',TO_DATE('1998-06-09', 'yyyy/mm/dd'),1 );


INSERT INTO Clients(Username,Password,Last_Login)
VALUES('Ivan','12345',TO_DATE('2019-03-03', 'yyyy/mm/dd'));

INSERT INTO Clients(Username,Password,Last_Login)
VALUES('Pesho','12345',TO_DATE('2020-02-03', 'yyyy/mm/dd'));

INSERT INTO Clients(Username,Password,Last_Login)
VALUES('Gosho','12345',TO_DATE('2020-01-01', 'yyyy/mm/dd'));

INSERT INTO Clients(Username,Password,Last_Login)
VALUES('Gosho','12345',TO_DATE('2020-02-18', 'yyyy/mm/dd'));

INSERT INTO Clients(Username,Password,Last_Login)
VALUES('Gosho','12345',TO_DATE('2020-02-17', 'yyyy/mm/dd'));

INSERT INTO Clients(Username,Password,Last_Login)
VALUES('Tosho','12345',TO_DATE('2010-01-01', 'yyyy/mm/dd'));

/*?	Find information about all departments names*/
SELECT Name FROM Department;

/*?	Find the salary of each employee*/
SELECT Salary FROM Employee;

/*?	Find the full name of each employee*/
SELECT FirstName, LastName 
FROM Employee;

/*?	Create a query that produces an employ email address by using the employee first and last name. 
The user E-mail consists of first name and last name concatenated by a full stop. The domain of the E-mail is fakecompany.com. 
The result must be produced in a separate column named Full name*/
SELECT CONCAT(CONCAT(FirstName, LastName),'fakecompany.com')
FROM Employee;

/*?	Find all employ with job title Senior executive*/
SELECT * FROM Employee
WHERE JobTitle = 'Senior';

/*?	Find all employs with name starts with letter S*/
SELECT * FROM Employee
WHERE FirstName LIKE 'S__%';

/*?	Find all employees with a name that contains the letter l*/
SELECT * FROM Employee
WHERE FirstName LIKE '%l%';

/*?	Find all employees that have a salary in the range 2000 – 3000*/
SELECT * FROM Employee
WHERE Salary < 3000 AND Salary > 2000;

/*?	Find all employees that have salaries 2500 / 3000 / 3500 / 5000*/
SELECT * FROM Employee
WHERE Salary = 2500 OR Salary = 3000 OR Salary = 3500 OR Salary = 5000;

/*?	Find all employees that do not have a manager*/
SELECT * FROM Employee
WHERE Manager_ID IS NULL;

/*?	Find all employees that have a senior position in the company and have a salary greater than 5000.
Order them in decreasing order and by alphabetical order by there first name.*/
SELECT * FROM Employee 
WHERE JobTitle = 'Senior' AND Salary > 5000
ORDER BY FirstName;

/*?	Find the top 5 best-paid employees.*/
SELECT *
FROM (select * from Employee ORDER BY Salary DESC) suppliers2
WHERE rownum <= 5
ORDER BY rownum;

/*?	Find all employees and their addresses*/
SELECT FirstName, Address 
FROM Employee;

/*?	Find all employees and their manager*/
SELECT E.FirstName,M.FirstName
FROM EMPLOYEE E  JOIN EMPLOYEE M
ON E.MANAGER_ID = M.EMPLOYEE_ID
GROUP BY E.FirstName,M.FirstName;

/*?	Find all employees along with their manager and address*/
SELECT E.FirstName,M.FirstName,M.Address
FROM EMPLOYEE E  JOIN EMPLOYEE M
ON E.MANAGER_ID = M.EMPLOYEE_ID
GROUP BY E.FirstName,M.FirstName,M.Address;

/*?	Find all departments and all town names as a single list*/
SELECT NAME,TOWN_NAME 
FROM DEPARTMENT;

/*●	Find all of the employees and the manager for each of them along with the employees that do not have a manager*/
SELECT E.FirstName,M.FirstName
FROM EMPLOYEE E LEFT JOIN EMPLOYEE M
ON E.MANAGER_ID = M.EMPLOYEE_ID
GROUP BY E.FirstName,M.FirstName;

/*●	Find all employees from “Sales” and all from “Finance” who are hired between 1995 and 2005*/
SELECT E.FirstName, D.NAME
FROM EMPLOYEE E JOIN DEPARTMENT D
ON E.DEPARTMENT_ID = D.DEPARMENT_ID
WHERE D.NAME = 'Sales' OR D.NAME = 'Finance' AND HIRE_DATE BETWEEN TO_DATE ('1995/01/01', 'yyyy/mm/dd') AND TO_DATE ('2005/01/01', 'yyyy/mm/dd')
GROUP BY E.FirstName,D.NAME;

/*●	Find the full name and salary of the employee that takes minimal salary in the company.*/
SELECT *
FROM (select FirstName,LastName,Salary from Employee ORDER BY Salary ASC) suppliers2
WHERE rownum <= 1
ORDER BY rownum;

/*●	Find the names and the salary of the employees that have a salary that is up to 10% higher than the minimum salary for the company*/
SELECT FirstName,LastName,Salary
FROM EMPLOYEE
WHERE SALARY > 0.1*(SELECT MIN(SALARY) FROM EMPLOYEE) + (SELECT MIN(SALARY) FROM EMPLOYEE)
GROUP BY FirstName,LastName,Salary;


/*●	Find the full name salary and the department of the employees that take the minimum salary in their department.*/

SELECT E.FIRSTNAME,E.SALARY,D.NAME
FROM EMPLOYEE E JOIN DEPARTMENT D
ON E.DEPARTMENT_ID = D.DEPARMENT_ID
GROUP BY D.NAME,E.FIRSTNAME,E.SALARY
HAVING SALARY = ANY(SELECT MIN(SALARY) FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPARTMENT_ID = D.DEPARMENT_ID GROUP BY D.DEPARMENT_ID);

SELECT *FROM EMPLOYEE;


/*●	Find the average salary in all department list the department name and the average salary*/
SELECT D.NAME,AVG(SALARY)
FROM DEPARTMENT D JOIN EMPLOYEE
ON D.DEPARMENT_ID = EMPLOYEE.DEPARTMENT_ID
GROUP BY D.NAME;

/*●	Find the number of employee in all the departments. List the department and the number of employees in it*/
SELECT D.NAME,COUNT(E.DEPARTMENT_ID) AS NumberOfEmployees
FROM EMPLOYEE E JOIN DEPARTMENT D
ON E.DEPARTMENT_ID = D.DEPARMENT_ID
GROUP BY D.NAME;

/*●	Group all employee by the manager*/
SELECT M.FirstName, COUNT(M.EMPLOYEE_ID) AS NumberOfEmployees
FROM EMPLOYEE E JOIN EMPLOYEE M
ON E.MANAGER_ID = M.EMPLOYEE_ID
GROUP BY M.FirstName;

/*●	Find all employees whose names are exactly 5 characters*/
SELECT FirstName FROM EMPLOYEE
WHERE LENGTH(FirstName) = 5;

/*●	Create a view that shows all clients that have been in the system today*/
CREATE VIEW LogToday AS
  SELECT USERNAME
  FROM CLIENTS
  WHERE LAST_LOGIN  > SYSDATE - 24/24;
  
SELECT * FROM LogToday;

/*●	Change the passwords of all clients that are absent from the system since 10.03.2010*/
UPDATE Clients 
SET Password = '54321'
WHERE Last_Login < TO_DATE ('2010/03/10', 'yyyy/mm/dd');

select * from clients

/*●	Delete all clients without password*/
DELETE FROM CLIENTS
WHERE PASSWORD = '';

/*●	Display the town with max employees */
SELECT MAX (NumberOfEmployees) 
FROM (SELECT E.DEPARTMENT_ID,COUNT(E.DEPARTMENT_ID) AS NumberOfEmployees
FROM EMPLOYEE E JOIN DEPARTMENT D
ON E.DEPARTMENT_ID = D.DEPARMENT_ID
GROUP BY E.DEPARTMENT_ID);

/*Create a transaction that deletes the information from the tables, drop all the tables and reroll the transaction at the end of the process*/
BEGIN

SAVEPOINT < BeforeRollBack >;
    Drop table Clients,
    Drop table Department,
    Drop table Employee CASCADE CONSTRAINTS;
    
ROLLBACK [TO SAVEPOINT < BeforeRollBack>]; 
END;
    





